### ISSUE TITLE
Apparent bug for Python 3

### ISSUE THREAD

**Issue by jtarbouriech** [mehrdadn/SOTA-Py#1]
Hi,
Using Python 3.5, the code doesn't compile for certain couples of (source, dest).
For example, running:
python Main.py --source=65280072.0 --dest=65319643.0 --budget=1800 --network="data/sf.osm.json"
generates a "TypeError: unorderable types: tuple() < NoneType()" (at line number 1061).
I believe it is a Python 3 compatibility issue since Python 3 ignores the cmp() method and doesn't have a cmp() function anymore.

**Comment by mehrdadn** [comment]
Thanks! I just pushed a fix for this issue.

**Comment by mehrdadn** [comment]
Okay, it seems to me that the secondary thrashing issue I mentioned might not be a bug—rather, you might have just found an exponential-time edge case for the algorithm (and the first one I'm aware of)!
I'll close this pull request since the original issue is address, but if I have any further updates on the other one I will provide them. Thanks again so much for the report!

**Comment by mehrdadn** [comment]
Update: I found the issue. It seems to be that I forgot to check for loops in the path. Will fix that soon!

**Comment by mehrdadn** [comment]
And finally, fixed!
